services:
    db:
        image: postgres:17
        container_name: db
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=postgres
        volumes:
            - ./volumes/postgresql:/var/lib/postgresql/data
        networks:
            - odoo_network
        restart: always
        ports:
            - "5432:5432"

    odoo:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: odoo
        depends_on:
            - db
        environment:
            - HOST=db
            - USER=${POSTGRES_USER}
            - PASSWORD=${POSTGRES_PASSWORD}
            - PORT=5432
        volumes:
            - ./volumes/odoo:/var/lib/odoo
            - ./addons:/mnt/extra-addons
            - ./etc:/etc/odoo
            - ./odoo.conf:/etc/odoo/odoo.conf
        networks:
            - odoo_network
        restart: always
        ports:
            - "8069:8069"
    nginx:
        image: nginx:latest
        container_name: nginx
        depends_on:
            - odoo
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        restart: always
        networks:
            - odoo_network
networks:
    odoo_network:
        driver: bridge

volumes:
    postgresql:
